publisher_forward_position_controller:
  ros__parameters:

    wait_sec_between_publish: 5
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2"]
    pos1: [0, 0, 0, 0, 0]
    pos2: [-10, -10, -10, -10, -1]

