controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["rueda_izq_delantera_joint", "rueda_izq_trasera_joint"]
    right_wheel_names: ["rueda_der_delantera_joint", "rueda_der_trasera_joint"]

    publish_rate: 50.0

    base_frame_id: base_link
    wheel_separation: 0.245
    wheel_radius: 0.055

    use_stamped_vel: false