controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - rueda_izq_delantera_joint
      - rueda_der_delantera_joint
      - rueda_izq_trasera_joint
      - rueda_der_trasera_joint
      - aspersor_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      rueda_izq_delantera_joint:
        trajectory: 0.05
        goal: 0.03
      rueda_der_delantera_joint:
        trajectory: 0.05
        goal: 0.03
      rueda_izq_trasera_joint:
        trajectory: 0.05
        goal: 0.03
      rueda_der_trasera_joint:
        trajectory: 0.05
        goal: 0.03
      aspersor_joint:
        trajectory: 0.05
        goal: 0.03